#!/usr/bin/env bash


CONFIG_FILE="${CONFIG_FILE:-/etc/fifo-rsh/config}"

if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
fi

MASTER_PIPE="${MASTER_PIPE:-master_pipe}"
SLAVES="${SLAVES:-8}"
SLAVE_FILES_DIRECTORY="${SLAVE_FILES_DIRECTORY:-fifo}"

declare -a SLAVE_FILES
declare -i CURRENT_PROCESS
CURRENT_PROCESS=0

main() {
    mkfifo "$MASTER_PIPE" || exit 1

    for i in `seq $SLAVES`; do
        file="${SLAVE_FILES_DIRECTORY}/fifo_$i"
        mkfifo "$file" || exit 1
        SLAVE_FILES[$i]="$file"
        ./worker $file &
    done


    while true; do
        declare -a requests
        requests=()

        while IFS= read -r -d '' match; do
            requests+=("$match")
        done < <(perl -0777 -ne 'while (/BEGIN-REQ\s*\[(.*?)\]\s*END-REQ/gs) { print "$1\0" }' "$MASTER_PIPE")

        for request in "${requests[@]}"
        do
            file="${request%%:*}"
            command="${request#*:}"
            printf '%s\n%s\n' "$file" "$command" > "${SLAVE_FILES[$(( CURRENT_PROCESS + 1 ))]}"

            CURRENT_PROCESS=$(( (CURRENT_PROCESS + 1) % SLAVES ))
        done
    done
}

cleanup() {
    kill $(jobs -p) 2>/dev/null
    rm -f "${SLAVE_FILES[@]}"
    rm -f "$MASTER_PIPE"
}

trap cleanup EXIT
main "$@"
