#!/usr/bin/env bash

MASTER_PIPE="master_pipe"
SLAVES=8
SLAVE_FILES_DIRECTORY="fifo"
CLIENT_FILE_SHAPE="/tmp/rshd-%s"
declare -a SLAVE_FILES
declare -i CURRENT_PROCESS
CURRENT_PROCESS=0

main() {
    cd `dirname "$0"`

    mkfifo "$MASTER_PIPE" || exit 1

    for i in `seq $SLAVES`; do
        file="${SLAVE_FILES_DIRECTORY}/fifo_$i"
        mkfifo "$file" || exit 1
        SLAVE_FILES[$i]="$file"
        ./worker $file &
    done


    while true; do
        declare -a requests
        requests=()

        while IFS= read -r -d '' match; do
            requests+=("$match")
        done < <(perl -0777 -ne 'while (/BEGIN-REQ\s*\[(.*?)\]\s*END-REQ/gs) { print "$1\0" }' "$MASTER_PIPE")

        for request in "${requests[@]}"
        do
            pid="${request%%:*}"
            command="${request#*:}"
            printf '%s\n%s\n' "$(printf "$CLIENT_FILE_SHAPE" "$pid")" "$command" > "${SLAVE_FILES[$(( CURRENT_PROCESS + 1 ))]}"

            CURRENT_PROCESS=$(( (CURRENT_PROCESS + 1) % SLAVES ))
        done
    done
}

cleanup() {
    kill $(jobs -p) 2>/dev/null
    rm -f "${SLAVE_FILES[@]}"
    rm -f "$MASTER_PIPE"
}

trap cleanup EXIT
main "$@"
