#!/usr/bin/env bash

CLIENT_FILE_SHAPE="/tmp/fifo-rsh-%s"
REQUEST_SHAPE="${REQUEST_SHAPE:-BEGIN-REQ[%s:%s]END-REQ}"

if [[ $# -ne 1 ]]; then
    2>&1 echo "Usage: $0 {master-pipe}"
    exit 1
fi

while true; do
    echo -n "rshd>"
    read command

    client_file=`printf "$CLIENT_FILE_SHAPE" "$$"`
    mkfifo "$client_file" || exit 1

    printf "$REQUEST_SHAPE" "$client_file" "$command" >"$1"

    cat "$client_file"
    rm -f "$client_file"
done
